version: '3.7'
services:
  be-mockoon:
    container_name: counter-be
    image: mockoon/cli
    ports:
      - "3005:3005"
    volumes:
      - ${COUNTER_VOL}/counter_be.json:/data:ro
    command: -d data
  fe:
    container_name: counter-fe
    image: counter:latest
    build:
      context: ./counter-testing
      dockerfile: dockerfile
    ports:
      - "80:80"
    restart:
       always
